<?php
$this->htmlElement('body')->appendAttribute('class', 'items search');
?>
<div class="clearfix">&nbsp;</div>

<h2><?php echo $this->translate('Advanced item search'); ?></h2>

<div class="clearfix">&nbsp;</div>

<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
    <?php echo $this->partial(
        'common/advanced-search',
        ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']
    ); ?>

    <div class="clearfix">&nbsp;</div>
    <div id="page-actions">
        <input class="button" type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search')); ?>">
    </div>
</form>

<div class="clearfix">&nbsp;</div>