<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headScript()->prependFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/lightgallery.min.js'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightslider.min.css'));
$lightMedia = [];
$otherMedia = [];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if ((strpos($mediaType, 'image') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>
<div class="clearfix">&nbsp;</div>
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>

<?php $this->trigger('view.show.before'); ?>
<?php if (count($lightMedia) > 0): ?>
<ul id="itemfiles" class="media-list">
    <?php foreach ($lightMedia as $media): ?>
        <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
        <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>" class="media resource">
            <?php echo $media->render(); ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<!---->
<?php //echo $item->displayValues(); ?>
<!---->
<?php if (count($otherMedia) > 0): ?>
<div id="other-media" class="property">
    <h4><?php echo $this->translate('Other Media'); ?></h4>
    <div class="row">
        <?php foreach($otherMedia as $media): ?>
            <div class="col-md-2 value">
                <a href="<?php echo $media->siteUrl(); ?>" title="<?php echo $media->displayTitle(); ?>">
                    <img src="<?php echo $escape($media->thumbnailUrl('medium')); ?>" alt="">
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
<!---->
<?php //$itemSets = $item->itemSets(); ?>
<?php //if (count($itemSets) > 0): ?>
<!--<div class="property">-->
<!--    <h4>--><?php //echo $this->translate('Item sets'); ?><!--</h4>-->
<!--    --><?php //foreach ($item->itemSets() as $itemSet): ?>
<!--    <div class="value"><a href="--><?php //echo $escape($itemSet->url()); ?><!--">--><?php //echo $itemSet->displayTitle(); ?><!--</a></div>-->
<!--    --><?php //endforeach; ?>
<!--</div>-->
<?php //endif; ?>
<!---->
<?php
//$page = $this->params()->fromQuery('page', 1);
//$property = $this->params()->fromQuery('property');
//$subjectValues = $item->displaySubjectValues($page, 25, $property);
//?>
<?php //if ($subjectValues): ?>
<!--<div id="item-linked">-->
<!--    <h3>--><?php //echo $this->translate('Linked resources'); ?><!--</h3>-->
<!--    --><?php //echo $subjectValues; ?>
<!--</div>-->
<?php //endif; ?>
<!---->
<?php //$this->trigger('view.show.after'); ?>
<!---->
<div class="clearfix">&nbsp;</div>

<script src="<?php echo $this->assetUrl('js/lg-video.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->assetUrl('js/lg-zoom.js'); ?>" type="text/javascript"></script>

<script>
    jQuery(document).ready(function() {
      $('#itemfiles').lightSlider({
          mode: 'fade',
          autoWidth: true,
          vertical: false,
          verticalHeight: 300,
          adaptiveHeight: false,
          gallery: true,
          item: 1,
          loop: true,
          thumbItem: 15,
          slideMargin: 0,
          enableDrag: false,
          currentPagerPosition: 'middle',
          onSliderLoad: function(el) {
              el.lightGallery({
                  selector: '#itemfiles .media',
                  download: false,
                  zoom: true,
                  youtubePlayerParams: {
                      modestbranding: 1,
                      showinfo: 0,
                      rel: 0,
                      controls: 1
                  },
                  vimeoPlayerParams: {
                      byline : 0,
                      portrait : 0,
                      color : 'A90707'
                  },
              });
          }
      });
    });
</script>

<div class="meta-properties">
    <?php echo $item->displayValues(); ?>
</div>

<div class="property">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
        <h4><?php echo $this->translate('Item sets'); ?></h4>
        <?php foreach ($item->itemSets() as $itemSet): ?>
            <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<div class="clearfix">&nbsp;</div>

<hr />

<div class="clearfix">&nbsp;</div>


<?php //if (!$embedMedia && $itemMedia): ?>
<!--    <div class="media-list">-->
<!--        --><?php //foreach ($itemMedia as $media): ?>
<!--            --><?php //echo $media->linkPretty(); ?>
<!--        --><?php //endforeach; ?>
<!--    </div>-->
<?php //endif; ?>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $this->translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>

<div class="clearfix">&nbsp;</div>
